In [1]:
import numpy as np
import time

In [2]:
# let's declare the size
Size = 10000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result1 = [(x + y) for x, y in zip(list1, list2)]

print("Time for Python List in msec: ", (time.time() - start) )

# Calculating time for NumPy array
start = time.time()
result2 = (arr1 + arr2)

print("Time for NumPy array in msec: ", (time.time()- start) )

Time for Python List in msec:  0.026829242706298828
Time for NumPy array in msec:  0.0009591579437255859


In [3]:
# Define an array arr with integer elements 1,2,3 and 4
integerArray = np.array([1,2,3,4], int)

In [4]:
# We can access these elements by using index values
print(integerArray[0])

1


In [5]:
# We can also use ranges to access values
print(integerArray[:2])

[1 2]


In [6]:
# Find if a value exists in the array
# Returns true if value exists else returns false
print(3 in integerArray)

True


In [7]:
integerArray2 = np.array([5,6], int)
# Concatenate two arrays
print(np.concatenate((integerArray, integerArray2)))

[1 2 3 4 5 6]


In [8]:
# Array of zeros
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Array of ones with type int
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


In [10]:
# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Multidimensional array
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
floatArray.shape

(2, 3)

In [13]:
rangeArray.shape

(10,)

In [14]:
# Convert one dimensional to multidimensional arrays
rangeArray = rangeArray.reshape(5, 2)
print(rangeArray)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
# Convert multidimensional to one dimensional array
rangeArray = rangeArray.flatten()
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(arr1,'\n')
print(arr2,'\n')
print(np.concatenate((arr1, arr2)))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Operations

In [17]:
#Operations
print("Array 1 \n {}".format(arr1))

Array 1 
 [[1 2]
 [3 4]]


In [18]:

# Addition
print("Array 1 + Array 2\n {}".format(arr1 + arr2))

Array 1 + Array 2
 [[ 6  8]
 [10 12]]


In [19]:
# Multiplication
print("Array 1 * Array 2\n {}".format(arr1 * arr2))

Array 1 * Array 2
 [[ 5 12]
 [21 32]]


In [20]:
# Square root
print("Square root of Array 1\n {}".format(np.sqrt(arr1)))

Square root of Array 1
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [21]:
# Log
print("Square root of Array 1\n {}".format(np.log(arr1)))

Square root of Array 1
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


In [22]:
# Sum of array elements
print("Sum of elements of Array 1: {}".format(arr1.sum()))

Sum of elements of Array 1: 10


In [23]:
# Mean of array elements
print("Mean of elements of Array 1: {}".format(arr1.mean()))

Mean of elements of Array 1: 2.5


In [24]:
# Min of array elements
print("Min of elements of Array 1: {}".format(arr1.min()))

Min of elements of Array 1: 1


In [25]:
# max of array elements
print("Min of elements of Array 1: {}".format(arr1.max()))

Min of elements of Array 1: 4


In [26]:
# standard deviation of array elements
print("Min of elements of Array 1: {}".format(arr1.std()))

Min of elements of Array 1: 1.118033988749895


In [27]:
sampleArray = np.array([[5,2,3], [3,4,5], [1,1,1]], int)
print("Sample Array\n {}".format(sampleArray))

Sample Array
 [[5 2 3]
 [3 4 5]
 [1 1 1]]


In [28]:
# Get unqiue values
print("Unique values: {}".format(np.unique(sampleArray)))

Unique values: [1 2 3 4 5]


In [29]:
# Get diagonal values
print("Diagonal\n {}".format(sampleArray.diagonal()))

Diagonal
 [5 4 1]


In [30]:
# Sort values in the multidimensional array
print("Sorted\n {}".format(np.sort(sampleArray)))

Sorted
 [[2 3 5]
 [3 4 5]
 [1 1 1]]


## Random Arrays

In [31]:
# Random array
print("Random array: {}".format(np.random.rand(5)))

Random array: [0.28798608 0.2073742  0.13264189 0.33447403 0.92957334]


In [32]:
# Random matrix
print("Random matrix:\n {}".format(np.random.rand(5,4)))

Random matrix:
 [[0.4200963  0.8700877  0.40598868 0.19098059]
 [0.26671497 0.98599014 0.73923191 0.99262261]
 [0.15200268 0.47308212 0.74314601 0.22953586]
 [0.62612049 0.51151549 0.97135028 0.46495672]
 [0.25010186 0.54475042 0.16333069 0.84553247]]


In [33]:
# Random array of integers in a range (say 0-9)

#floor return the input part of the array
randomArray = np.floor(np.random.rand(10) * 10)

print("Random integer array: {}".format(randomArray))

Random integer array: [5. 1. 1. 2. 6. 9. 2. 3. 5. 3.]


In [34]:
# Futher simplification

print("Random matrix:\n{}".format(np.random.randint(0, 10, (2,5))))

print("Random matrix:\n{}".format(np.random.randint(0, 10, (5))))

Random matrix:
[[9 3 7 7 4]
 [0 5 7 8 6]]
Random matrix:
[7 4 9 2 1]


## How to extract all numbers between a given range from a numpy array?

In [35]:
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
output_array = a[index]
output_array

array([ 5,  6,  7,  8,  9, 10])

In [36]:
# Method 2
output_array = a[(a >= 5) & (a <= 10)]
output_array

array([ 5,  6,  7,  8,  9, 10])

## How to print only 3 decimal places in python numpy array?

In [37]:
# Create the random array
rand_arr = np.random.random([5,3])

rand_arr

array([[0.06970165, 0.13906716, 0.24519543],
       [0.63438366, 0.18884485, 0.67695009],
       [0.14132219, 0.1656968 , 0.15418362],
       [0.23758979, 0.1685461 , 0.88187467],
       [0.18108258, 0.68633029, 0.76732925]])

In [38]:
# Limit to 3 decimal places
np.set_printoptions(precision=2)
rand_arr[:4]

array([[0.07, 0.14, 0.25],
       [0.63, 0.19, 0.68],
       [0.14, 0.17, 0.15],
       [0.24, 0.17, 0.88]])

## How to replace all values greater than a given value to a given cutoff?

In [39]:
np.random.seed(10)
a = np.random.uniform(1,50, 30)
a

array([38.79,  2.02, 32.05, 37.69, 25.43, 12.02, 10.71, 38.27,  9.29,
        5.33, 34.58, 47.72,  1.19, 26.1 , 40.82, 31.01, 36.37, 15.3 ,
       45.97, 36.01, 27.58,  7.97, 19.29, 34.03, 22.65, 22.27, 31.27,
       26.14, 32.87, 30.45])

In [40]:
# Solution 1: Using np.clip
output_array = np.clip(a, a_min=10, a_max=30)
output_array

array([30.  , 10.  , 30.  , 30.  , 25.43, 12.02, 10.71, 30.  , 10.  ,
       10.  , 30.  , 30.  , 10.  , 26.1 , 30.  , 30.  , 30.  , 15.3 ,
       30.  , 30.  , 27.58, 10.  , 19.29, 30.  , 22.65, 22.27, 30.  ,
       26.14, 30.  , 30.  ])

In [41]:
# Solution 2: Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[30.   10.   30.   30.   25.43 12.02 10.71 30.   10.   10.   30.   30.
 10.   26.1  30.   30.   30.   15.3  30.   30.   27.58 10.   19.29 30.
 22.65 22.27 30.   26.14 30.   30.  ]


## How to drop all missing values from a numpy array?

In [42]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

## How to get the positions of top n values from a numpy array?

In [43]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 10)

# Solution:
print(a)
a.argsort()

[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18]


array([4, 5, 8, 1, 2, 0, 9, 6, 7, 3], dtype=int64)

In [44]:
a.argsort()[-3:]

array([6, 7, 3], dtype=int64)

In [45]:
a[a.argsort()[-3:]] #getting the value

array([33.87, 41.47, 42.39])